#pragma once

#define APP_WIFI_SSID "REPLACE_ME"
#define APP_WIFI_PASSWORD "REPLACE_ME"
#define APP_PEER_HOST "REPLACE_ME"
#define APP_MQTT_PORT 14567
#define APP_WIFI_TIMEOUT_MS 15000
#define APP_DEVICE_ID "esp32s3"

#define APP_AI_STREAM_ID 0
#define APP_SENSOR_STREAM_ID 4
#define APP_IMAGE_STREAM_ID 8

#define APP_EXPERIMENT_PRESET_HYBRID_BASELINE 0
#define APP_EXPERIMENT_PRESET_RELIABILITY_BIASED 1
#define APP_EXPERIMENT_PRESET_THROUGHPUT_BIASED 2
#define APP_EXPERIMENT_PRESET_STREAM_FIRST_HYBRID 3

#define APP_TRANSPORT_MODE_STREAM_ONLY 1
#define APP_TRANSPORT_MODE_DATAGRAM_ONLY 2
#define APP_TRANSPORT_MODE_HYBRID 3

#ifndef APP_TRANSPORT_MODE
#define APP_TRANSPORT_MODE APP_TRANSPORT_MODE_HYBRID
#endif

#ifndef APP_EXPERIMENT_PRESET
#define APP_EXPERIMENT_PRESET APP_EXPERIMENT_PRESET_STREAM_FIRST_HYBRID
#endif

#if APP_EXPERIMENT_PRESET == APP_EXPERIMENT_PRESET_RELIABILITY_BIASED
#define APP_CONTROL_PERIOD_MS 60
#define APP_IMAGE_DATAGRAM_BUDGET 900
#define APP_QADS_POLICY_MODE 1
#elif APP_EXPERIMENT_PRESET == APP_EXPERIMENT_PRESET_THROUGHPUT_BIASED
#define APP_CONTROL_PERIOD_MS 40
#define APP_IMAGE_DATAGRAM_BUDGET 1300
#define APP_QADS_POLICY_MODE 2
#elif APP_EXPERIMENT_PRESET == APP_EXPERIMENT_PRESET_STREAM_FIRST_HYBRID
#define APP_CONTROL_PERIOD_MS 50
#define APP_IMAGE_DATAGRAM_BUDGET 1200
#define APP_QADS_POLICY_MODE 3
#else
#define APP_CONTROL_PERIOD_MS 50
#define APP_IMAGE_DATAGRAM_BUDGET 1200
#define APP_QADS_POLICY_MODE 0
#endif

#define APP_MAX_PAYLOAD_SIZE 1024

#ifndef APP_NET_TX_STACK_SAMPLE_INTERVAL
#define APP_NET_TX_STACK_SAMPLE_INTERVAL 10
#endif

#ifndef APP_STRESS_MODE_ENABLE
#define APP_STRESS_MODE_ENABLE 0
#endif

#ifndef APP_STRESS_DATAGRAM_BURST_COUNT
#define APP_STRESS_DATAGRAM_BURST_COUNT 12
#endif

#ifndef APP_STRESS_DATAGRAM_PAYLOAD_SIZE
#define APP_STRESS_DATAGRAM_PAYLOAD_SIZE 512
#endif

#ifndef APP_STRESS_INTER_BURST_DELAY_MS
#define APP_STRESS_INTER_BURST_DELAY_MS 0
#endif
